[package]
name = "enums"
version = "0.0.1"
authors = ["Calixte Denizet <cdenizet@mozilla.com>"]
edition = "2021"

[dependencies]
clap = { version = "^3.2", features = ["derive"] }
askama = "^0.11"

tree-sitter = ">= 0.19, < 0.21"
tree-sitter-typescript = "=0.20.0"
tree-sitter-javascript = "=0.20.0"
tree-sitter-rust = "=0.20.1"
tree-sitter-python = { git = "https://github.com/tree-sitter/tree-sitter-python", branch = "master" }
tree-sitter-java = { git = "https://github.com/hyperlog/tree-sitter-java", branch = "master" }
tree-sitter-preproc = { path = "../tree-sitter-preproc", version = "=0.20.0" }
tree-sitter-ccomment = { path = "../tree-sitter-ccomment", version = "=0.20.0" }
tree-sitter-mozcpp = { path = "../tree-sitter-mozcpp", version = "=0.20.1" }
tree-sitter-mozjs = { path = "../tree-sitter-mozjs", version = "=0.20.0" }

[profile.release]
strip = "debuginfo"
