[package]
name = "enums"
version = "0.0.1"
authors = ["Calixte Denizet <cdenizet@mozilla.com>"]
edition = "2018"
build = "../build.rs"

[build-dependencies]
cc = "^1.0"
phf_codegen = "^0.8"

[dependencies]
enum-iterator = "^0.6"
clap = "^2.33"
askama = "^0.10"
phf_codegen = "^0.8"
libc = "^0.2"

tree-sitter = "^0.17"
tree-sitter-java = "^0.19"
tree-sitter-preproc = { path = "../tree-sitter-preproc", version = "^0.17" }
tree-sitter-ccomment = { path = "../tree-sitter-ccomment", version = "^0.17" }
tree-sitter-mozcpp = { path = "../tree-sitter-mozcpp", version = "^0.17" }
tree-sitter-mozjs = { path = "../tree-sitter-mozjs", version = "^0.17" }
